/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedCompanyActivityRouteImport } from './routes/_authenticated/company.activity'
import { Route as AuthenticatedCompanyApartmentsRouteImport } from './routes/_authenticated/company.apartments'
import { Route as AuthenticatedCompanyAssistantRouteImport } from './routes/_authenticated/company.assistant'
import { Route as AuthenticatedCompanyDashboardRouteImport } from './routes/_authenticated/company.dashboard'
import { Route as AuthenticatedCompanyDocumentsRouteImport } from './routes/_authenticated/company.documents'
import { Route as AuthenticatedCompanyManagersRouteImport } from './routes/_authenticated/company.managers'
import { Route as AuthenticatedCompanyMeetingsRouteImport } from './routes/_authenticated/company.meetings'
import { Route as AuthenticatedCompanyNotificationsRouteImport } from './routes/_authenticated/company.notifications'
import { Route as AuthenticatedCompanyProjectsRouteImport } from './routes/_authenticated/company.projects'
import { Route as AuthenticatedCompanyRequestsRouteImport } from './routes/_authenticated/company.requests'
import { Route as AuthenticatedCompanySearchRouteImport } from './routes/_authenticated/company.search'
import { Route as AuthenticatedCompanySettingsRouteImport } from './routes/_authenticated/company.settings'
import { Route as AuthenticatedCompanyStagesRouteImport } from './routes/_authenticated/company.stages'
import { Route as AuthenticatedCompanyTeamRouteImport } from './routes/_authenticated/company.team'
import { Route as AuthenticatedCompanyTenantsRouteImport } from './routes/_authenticated/company.tenants'
import { Route as AuthenticatedManagerActivityRouteImport } from './routes/_authenticated/manager.activity'
import { Route as AuthenticatedManagerAssistantRouteImport } from './routes/_authenticated/manager.assistant'
import { Route as AuthenticatedManagerDashboardRouteImport } from './routes/_authenticated/manager.dashboard'
import { Route as AuthenticatedManagerDocumentsRouteImport } from './routes/_authenticated/manager.documents'
import { Route as AuthenticatedManagerMeetingsRouteImport } from './routes/_authenticated/manager.meetings'
import { Route as AuthenticatedManagerNotificationsRouteImport } from './routes/_authenticated/manager.notifications'
import { Route as AuthenticatedManagerPhotosRouteImport } from './routes/_authenticated/manager.photos'
import { Route as AuthenticatedManagerProjectsRouteImport } from './routes/_authenticated/manager.projects'
import { Route as AuthenticatedManagerRequestsRouteImport } from './routes/_authenticated/manager.requests'
import { Route as AuthenticatedManagerSearchRouteImport } from './routes/_authenticated/manager.search'
import { Route as AuthenticatedManagerSettingsRouteImport } from './routes/_authenticated/manager.settings'
import { Route as AuthenticatedManagerStagesRouteImport } from './routes/_authenticated/manager.stages'
import { Route as AuthenticatedManagerTasksRouteImport } from './routes/_authenticated/manager.tasks'
import { Route as AuthenticatedManagerTeamRouteImport } from './routes/_authenticated/manager.team'
import { Route as AuthenticatedManagerUploadRouteImport } from './routes/_authenticated/manager.upload'
import { Route as AuthenticatedTenantAssistantRouteImport } from './routes/_authenticated/tenant.assistant'
import { Route as AuthenticatedTenantDashboardRouteImport } from './routes/_authenticated/tenant.dashboard'
import { Route as AuthenticatedTenantDocumentsRouteImport } from './routes/_authenticated/tenant.documents'
import { Route as AuthenticatedTenantMeetingsRouteImport } from './routes/_authenticated/tenant.meetings'
import { Route as AuthenticatedTenantNotificationsRouteImport } from './routes/_authenticated/tenant.notifications'
import { Route as AuthenticatedTenantPhotosRouteImport } from './routes/_authenticated/tenant.photos'
import { Route as AuthenticatedTenantProjectRouteImport } from './routes/_authenticated/tenant.project'
import { Route as AuthenticatedTenantRequestsRouteImport } from './routes/_authenticated/tenant.requests'
import { Route as AuthenticatedTenantSettingsRouteImport } from './routes/_authenticated/tenant.settings'
import { Route as AuthenticatedTenantTimelineRouteImport } from './routes/_authenticated/tenant.timeline'
import { Route as AuthenticatedCompanyProjectsProjectIdRouteImport } from './routes/_authenticated/company.projects.$projectId'
import { Route as AuthenticatedCompanyStagesStageIdRouteImport } from './routes/_authenticated/company.stages.$stageId'
import { Route as AuthenticatedManagerProjectsProjectIdRouteImport } from './routes/_authenticated/manager.projects.$projectId'
import { Route as AuthenticatedManagerTasksTaskIdRouteImport } from './routes/_authenticated/manager.tasks.$taskId'
import { Route as AuthenticatedTenantTimelineStageIdRouteImport } from './routes/_authenticated/tenant.timeline.$stageId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCompanyActivityRoute =
  AuthenticatedCompanyActivityRouteImport.update({
    id: '/company/activity',
    path: '/company/activity',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCompanyApartmentsRoute =
  AuthenticatedCompanyApartmentsRouteImport.update({
    id: '/company/apartments',
    path: '/company/apartments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCompanyAssistantRoute =
  AuthenticatedCompanyAssistantRouteImport.update({
    id: '/company/assistant',
    path: '/company/assistant',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCompanyDashboardRoute =
  AuthenticatedCompanyDashboardRouteImport.update({
    id: '/company/dashboard',
    path: '/company/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCompanyDocumentsRoute =
  AuthenticatedCompanyDocumentsRouteImport.update({
    id: '/company/documents',
    path: '/company/documents',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCompanyManagersRoute =
  AuthenticatedCompanyManagersRouteImport.update({
    id: '/company/managers',
    path: '/company/managers',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCompanyMeetingsRoute =
  AuthenticatedCompanyMeetingsRouteImport.update({
    id: '/company/meetings',
    path: '/company/meetings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCompanyNotificationsRoute =
  AuthenticatedCompanyNotificationsRouteImport.update({
    id: '/company/notifications',
    path: '/company/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCompanyProjectsRoute =
  AuthenticatedCompanyProjectsRouteImport.update({
    id: '/company/projects',
    path: '/company/projects',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCompanyRequestsRoute =
  AuthenticatedCompanyRequestsRouteImport.update({
    id: '/company/requests',
    path: '/company/requests',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCompanySearchRoute =
  AuthenticatedCompanySearchRouteImport.update({
    id: '/company/search',
    path: '/company/search',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCompanySettingsRoute =
  AuthenticatedCompanySettingsRouteImport.update({
    id: '/company/settings',
    path: '/company/settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCompanyStagesRoute =
  AuthenticatedCompanyStagesRouteImport.update({
    id: '/company/stages',
    path: '/company/stages',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCompanyTeamRoute =
  AuthenticatedCompanyTeamRouteImport.update({
    id: '/company/team',
    path: '/company/team',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCompanyTenantsRoute =
  AuthenticatedCompanyTenantsRouteImport.update({
    id: '/company/tenants',
    path: '/company/tenants',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedManagerActivityRoute =
  AuthenticatedManagerActivityRouteImport.update({
    id: '/manager/activity',
    path: '/manager/activity',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedManagerAssistantRoute =
  AuthenticatedManagerAssistantRouteImport.update({
    id: '/manager/assistant',
    path: '/manager/assistant',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedManagerDashboardRoute =
  AuthenticatedManagerDashboardRouteImport.update({
    id: '/manager/dashboard',
    path: '/manager/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedManagerDocumentsRoute =
  AuthenticatedManagerDocumentsRouteImport.update({
    id: '/manager/documents',
    path: '/manager/documents',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedManagerMeetingsRoute =
  AuthenticatedManagerMeetingsRouteImport.update({
    id: '/manager/meetings',
    path: '/manager/meetings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedManagerNotificationsRoute =
  AuthenticatedManagerNotificationsRouteImport.update({
    id: '/manager/notifications',
    path: '/manager/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedManagerPhotosRoute =
  AuthenticatedManagerPhotosRouteImport.update({
    id: '/manager/photos',
    path: '/manager/photos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedManagerProjectsRoute =
  AuthenticatedManagerProjectsRouteImport.update({
    id: '/manager/projects',
    path: '/manager/projects',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedManagerRequestsRoute =
  AuthenticatedManagerRequestsRouteImport.update({
    id: '/manager/requests',
    path: '/manager/requests',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedManagerSearchRoute =
  AuthenticatedManagerSearchRouteImport.update({
    id: '/manager/search',
    path: '/manager/search',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedManagerSettingsRoute =
  AuthenticatedManagerSettingsRouteImport.update({
    id: '/manager/settings',
    path: '/manager/settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedManagerStagesRoute =
  AuthenticatedManagerStagesRouteImport.update({
    id: '/manager/stages',
    path: '/manager/stages',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedManagerTasksRoute =
  AuthenticatedManagerTasksRouteImport.update({
    id: '/manager/tasks',
    path: '/manager/tasks',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedManagerTeamRoute =
  AuthenticatedManagerTeamRouteImport.update({
    id: '/manager/team',
    path: '/manager/team',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedManagerUploadRoute =
  AuthenticatedManagerUploadRouteImport.update({
    id: '/manager/upload',
    path: '/manager/upload',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTenantAssistantRoute =
  AuthenticatedTenantAssistantRouteImport.update({
    id: '/tenant/assistant',
    path: '/tenant/assistant',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTenantDashboardRoute =
  AuthenticatedTenantDashboardRouteImport.update({
    id: '/tenant/dashboard',
    path: '/tenant/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTenantDocumentsRoute =
  AuthenticatedTenantDocumentsRouteImport.update({
    id: '/tenant/documents',
    path: '/tenant/documents',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTenantMeetingsRoute =
  AuthenticatedTenantMeetingsRouteImport.update({
    id: '/tenant/meetings',
    path: '/tenant/meetings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTenantNotificationsRoute =
  AuthenticatedTenantNotificationsRouteImport.update({
    id: '/tenant/notifications',
    path: '/tenant/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTenantPhotosRoute =
  AuthenticatedTenantPhotosRouteImport.update({
    id: '/tenant/photos',
    path: '/tenant/photos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTenantProjectRoute =
  AuthenticatedTenantProjectRouteImport.update({
    id: '/tenant/project',
    path: '/tenant/project',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTenantRequestsRoute =
  AuthenticatedTenantRequestsRouteImport.update({
    id: '/tenant/requests',
    path: '/tenant/requests',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTenantSettingsRoute =
  AuthenticatedTenantSettingsRouteImport.update({
    id: '/tenant/settings',
    path: '/tenant/settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTenantTimelineRoute =
  AuthenticatedTenantTimelineRouteImport.update({
    id: '/tenant/timeline',
    path: '/tenant/timeline',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCompanyProjectsProjectIdRoute =
  AuthenticatedCompanyProjectsProjectIdRouteImport.update({
    id: '/$projectId',
    path: '/$projectId',
    getParentRoute: () => AuthenticatedCompanyProjectsRoute,
  } as any)
const AuthenticatedCompanyStagesStageIdRoute =
  AuthenticatedCompanyStagesStageIdRouteImport.update({
    id: '/$stageId',
    path: '/$stageId',
    getParentRoute: () => AuthenticatedCompanyStagesRoute,
  } as any)
const AuthenticatedManagerProjectsProjectIdRoute =
  AuthenticatedManagerProjectsProjectIdRouteImport.update({
    id: '/$projectId',
    path: '/$projectId',
    getParentRoute: () => AuthenticatedManagerProjectsRoute,
  } as any)
const AuthenticatedManagerTasksTaskIdRoute =
  AuthenticatedManagerTasksTaskIdRouteImport.update({
    id: '/$taskId',
    path: '/$taskId',
    getParentRoute: () => AuthenticatedManagerTasksRoute,
  } as any)
const AuthenticatedTenantTimelineStageIdRoute =
  AuthenticatedTenantTimelineStageIdRouteImport.update({
    id: '/$stageId',
    path: '/$stageId',
    getParentRoute: () => AuthenticatedTenantTimelineRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/company/activity': typeof AuthenticatedCompanyActivityRoute
  '/company/apartments': typeof AuthenticatedCompanyApartmentsRoute
  '/company/assistant': typeof AuthenticatedCompanyAssistantRoute
  '/company/dashboard': typeof AuthenticatedCompanyDashboardRoute
  '/company/documents': typeof AuthenticatedCompanyDocumentsRoute
  '/company/managers': typeof AuthenticatedCompanyManagersRoute
  '/company/meetings': typeof AuthenticatedCompanyMeetingsRoute
  '/company/notifications': typeof AuthenticatedCompanyNotificationsRoute
  '/company/projects': typeof AuthenticatedCompanyProjectsRouteWithChildren
  '/company/requests': typeof AuthenticatedCompanyRequestsRoute
  '/company/search': typeof AuthenticatedCompanySearchRoute
  '/company/settings': typeof AuthenticatedCompanySettingsRoute
  '/company/stages': typeof AuthenticatedCompanyStagesRouteWithChildren
  '/company/team': typeof AuthenticatedCompanyTeamRoute
  '/company/tenants': typeof AuthenticatedCompanyTenantsRoute
  '/manager/activity': typeof AuthenticatedManagerActivityRoute
  '/manager/assistant': typeof AuthenticatedManagerAssistantRoute
  '/manager/dashboard': typeof AuthenticatedManagerDashboardRoute
  '/manager/documents': typeof AuthenticatedManagerDocumentsRoute
  '/manager/meetings': typeof AuthenticatedManagerMeetingsRoute
  '/manager/notifications': typeof AuthenticatedManagerNotificationsRoute
  '/manager/photos': typeof AuthenticatedManagerPhotosRoute
  '/manager/projects': typeof AuthenticatedManagerProjectsRouteWithChildren
  '/manager/requests': typeof AuthenticatedManagerRequestsRoute
  '/manager/search': typeof AuthenticatedManagerSearchRoute
  '/manager/settings': typeof AuthenticatedManagerSettingsRoute
  '/manager/stages': typeof AuthenticatedManagerStagesRoute
  '/manager/tasks': typeof AuthenticatedManagerTasksRouteWithChildren
  '/manager/team': typeof AuthenticatedManagerTeamRoute
  '/manager/upload': typeof AuthenticatedManagerUploadRoute
  '/tenant/assistant': typeof AuthenticatedTenantAssistantRoute
  '/tenant/dashboard': typeof AuthenticatedTenantDashboardRoute
  '/tenant/documents': typeof AuthenticatedTenantDocumentsRoute
  '/tenant/meetings': typeof AuthenticatedTenantMeetingsRoute
  '/tenant/notifications': typeof AuthenticatedTenantNotificationsRoute
  '/tenant/photos': typeof AuthenticatedTenantPhotosRoute
  '/tenant/project': typeof AuthenticatedTenantProjectRoute
  '/tenant/requests': typeof AuthenticatedTenantRequestsRoute
  '/tenant/settings': typeof AuthenticatedTenantSettingsRoute
  '/tenant/timeline': typeof AuthenticatedTenantTimelineRouteWithChildren
  '/company/projects/$projectId': typeof AuthenticatedCompanyProjectsProjectIdRoute
  '/company/stages/$stageId': typeof AuthenticatedCompanyStagesStageIdRoute
  '/manager/projects/$projectId': typeof AuthenticatedManagerProjectsProjectIdRoute
  '/manager/tasks/$taskId': typeof AuthenticatedManagerTasksTaskIdRoute
  '/tenant/timeline/$stageId': typeof AuthenticatedTenantTimelineStageIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/company/activity': typeof AuthenticatedCompanyActivityRoute
  '/company/apartments': typeof AuthenticatedCompanyApartmentsRoute
  '/company/assistant': typeof AuthenticatedCompanyAssistantRoute
  '/company/dashboard': typeof AuthenticatedCompanyDashboardRoute
  '/company/documents': typeof AuthenticatedCompanyDocumentsRoute
  '/company/managers': typeof AuthenticatedCompanyManagersRoute
  '/company/meetings': typeof AuthenticatedCompanyMeetingsRoute
  '/company/notifications': typeof AuthenticatedCompanyNotificationsRoute
  '/company/projects': typeof AuthenticatedCompanyProjectsRouteWithChildren
  '/company/requests': typeof AuthenticatedCompanyRequestsRoute
  '/company/search': typeof AuthenticatedCompanySearchRoute
  '/company/settings': typeof AuthenticatedCompanySettingsRoute
  '/company/stages': typeof AuthenticatedCompanyStagesRouteWithChildren
  '/company/team': typeof AuthenticatedCompanyTeamRoute
  '/company/tenants': typeof AuthenticatedCompanyTenantsRoute
  '/manager/activity': typeof AuthenticatedManagerActivityRoute
  '/manager/assistant': typeof AuthenticatedManagerAssistantRoute
  '/manager/dashboard': typeof AuthenticatedManagerDashboardRoute
  '/manager/documents': typeof AuthenticatedManagerDocumentsRoute
  '/manager/meetings': typeof AuthenticatedManagerMeetingsRoute
  '/manager/notifications': typeof AuthenticatedManagerNotificationsRoute
  '/manager/photos': typeof AuthenticatedManagerPhotosRoute
  '/manager/projects': typeof AuthenticatedManagerProjectsRouteWithChildren
  '/manager/requests': typeof AuthenticatedManagerRequestsRoute
  '/manager/search': typeof AuthenticatedManagerSearchRoute
  '/manager/settings': typeof AuthenticatedManagerSettingsRoute
  '/manager/stages': typeof AuthenticatedManagerStagesRoute
  '/manager/tasks': typeof AuthenticatedManagerTasksRouteWithChildren
  '/manager/team': typeof AuthenticatedManagerTeamRoute
  '/manager/upload': typeof AuthenticatedManagerUploadRoute
  '/tenant/assistant': typeof AuthenticatedTenantAssistantRoute
  '/tenant/dashboard': typeof AuthenticatedTenantDashboardRoute
  '/tenant/documents': typeof AuthenticatedTenantDocumentsRoute
  '/tenant/meetings': typeof AuthenticatedTenantMeetingsRoute
  '/tenant/notifications': typeof AuthenticatedTenantNotificationsRoute
  '/tenant/photos': typeof AuthenticatedTenantPhotosRoute
  '/tenant/project': typeof AuthenticatedTenantProjectRoute
  '/tenant/requests': typeof AuthenticatedTenantRequestsRoute
  '/tenant/settings': typeof AuthenticatedTenantSettingsRoute
  '/tenant/timeline': typeof AuthenticatedTenantTimelineRouteWithChildren
  '/company/projects/$projectId': typeof AuthenticatedCompanyProjectsProjectIdRoute
  '/company/stages/$stageId': typeof AuthenticatedCompanyStagesStageIdRoute
  '/manager/projects/$projectId': typeof AuthenticatedManagerProjectsProjectIdRoute
  '/manager/tasks/$taskId': typeof AuthenticatedManagerTasksTaskIdRoute
  '/tenant/timeline/$stageId': typeof AuthenticatedTenantTimelineStageIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/company/activity': typeof AuthenticatedCompanyActivityRoute
  '/_authenticated/company/apartments': typeof AuthenticatedCompanyApartmentsRoute
  '/_authenticated/company/assistant': typeof AuthenticatedCompanyAssistantRoute
  '/_authenticated/company/dashboard': typeof AuthenticatedCompanyDashboardRoute
  '/_authenticated/company/documents': typeof AuthenticatedCompanyDocumentsRoute
  '/_authenticated/company/managers': typeof AuthenticatedCompanyManagersRoute
  '/_authenticated/company/meetings': typeof AuthenticatedCompanyMeetingsRoute
  '/_authenticated/company/notifications': typeof AuthenticatedCompanyNotificationsRoute
  '/_authenticated/company/projects': typeof AuthenticatedCompanyProjectsRouteWithChildren
  '/_authenticated/company/requests': typeof AuthenticatedCompanyRequestsRoute
  '/_authenticated/company/search': typeof AuthenticatedCompanySearchRoute
  '/_authenticated/company/settings': typeof AuthenticatedCompanySettingsRoute
  '/_authenticated/company/stages': typeof AuthenticatedCompanyStagesRouteWithChildren
  '/_authenticated/company/team': typeof AuthenticatedCompanyTeamRoute
  '/_authenticated/company/tenants': typeof AuthenticatedCompanyTenantsRoute
  '/_authenticated/manager/activity': typeof AuthenticatedManagerActivityRoute
  '/_authenticated/manager/assistant': typeof AuthenticatedManagerAssistantRoute
  '/_authenticated/manager/dashboard': typeof AuthenticatedManagerDashboardRoute
  '/_authenticated/manager/documents': typeof AuthenticatedManagerDocumentsRoute
  '/_authenticated/manager/meetings': typeof AuthenticatedManagerMeetingsRoute
  '/_authenticated/manager/notifications': typeof AuthenticatedManagerNotificationsRoute
  '/_authenticated/manager/photos': typeof AuthenticatedManagerPhotosRoute
  '/_authenticated/manager/projects': typeof AuthenticatedManagerProjectsRouteWithChildren
  '/_authenticated/manager/requests': typeof AuthenticatedManagerRequestsRoute
  '/_authenticated/manager/search': typeof AuthenticatedManagerSearchRoute
  '/_authenticated/manager/settings': typeof AuthenticatedManagerSettingsRoute
  '/_authenticated/manager/stages': typeof AuthenticatedManagerStagesRoute
  '/_authenticated/manager/tasks': typeof AuthenticatedManagerTasksRouteWithChildren
  '/_authenticated/manager/team': typeof AuthenticatedManagerTeamRoute
  '/_authenticated/manager/upload': typeof AuthenticatedManagerUploadRoute
  '/_authenticated/tenant/assistant': typeof AuthenticatedTenantAssistantRoute
  '/_authenticated/tenant/dashboard': typeof AuthenticatedTenantDashboardRoute
  '/_authenticated/tenant/documents': typeof AuthenticatedTenantDocumentsRoute
  '/_authenticated/tenant/meetings': typeof AuthenticatedTenantMeetingsRoute
  '/_authenticated/tenant/notifications': typeof AuthenticatedTenantNotificationsRoute
  '/_authenticated/tenant/photos': typeof AuthenticatedTenantPhotosRoute
  '/_authenticated/tenant/project': typeof AuthenticatedTenantProjectRoute
  '/_authenticated/tenant/requests': typeof AuthenticatedTenantRequestsRoute
  '/_authenticated/tenant/settings': typeof AuthenticatedTenantSettingsRoute
  '/_authenticated/tenant/timeline': typeof AuthenticatedTenantTimelineRouteWithChildren
  '/_authenticated/company/projects/$projectId': typeof AuthenticatedCompanyProjectsProjectIdRoute
  '/_authenticated/company/stages/$stageId': typeof AuthenticatedCompanyStagesStageIdRoute
  '/_authenticated/manager/projects/$projectId': typeof AuthenticatedManagerProjectsProjectIdRoute
  '/_authenticated/manager/tasks/$taskId': typeof AuthenticatedManagerTasksTaskIdRoute
  '/_authenticated/tenant/timeline/$stageId': typeof AuthenticatedTenantTimelineStageIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/unauthorized'
    | '/profile'
    | '/settings'
    | '/company/activity'
    | '/company/apartments'
    | '/company/assistant'
    | '/company/dashboard'
    | '/company/documents'
    | '/company/managers'
    | '/company/meetings'
    | '/company/notifications'
    | '/company/projects'
    | '/company/requests'
    | '/company/search'
    | '/company/settings'
    | '/company/stages'
    | '/company/team'
    | '/company/tenants'
    | '/manager/activity'
    | '/manager/assistant'
    | '/manager/dashboard'
    | '/manager/documents'
    | '/manager/meetings'
    | '/manager/notifications'
    | '/manager/photos'
    | '/manager/projects'
    | '/manager/requests'
    | '/manager/search'
    | '/manager/settings'
    | '/manager/stages'
    | '/manager/tasks'
    | '/manager/team'
    | '/manager/upload'
    | '/tenant/assistant'
    | '/tenant/dashboard'
    | '/tenant/documents'
    | '/tenant/meetings'
    | '/tenant/notifications'
    | '/tenant/photos'
    | '/tenant/project'
    | '/tenant/requests'
    | '/tenant/settings'
    | '/tenant/timeline'
    | '/company/projects/$projectId'
    | '/company/stages/$stageId'
    | '/manager/projects/$projectId'
    | '/manager/tasks/$taskId'
    | '/tenant/timeline/$stageId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/unauthorized'
    | '/profile'
    | '/settings'
    | '/company/activity'
    | '/company/apartments'
    | '/company/assistant'
    | '/company/dashboard'
    | '/company/documents'
    | '/company/managers'
    | '/company/meetings'
    | '/company/notifications'
    | '/company/projects'
    | '/company/requests'
    | '/company/search'
    | '/company/settings'
    | '/company/stages'
    | '/company/team'
    | '/company/tenants'
    | '/manager/activity'
    | '/manager/assistant'
    | '/manager/dashboard'
    | '/manager/documents'
    | '/manager/meetings'
    | '/manager/notifications'
    | '/manager/photos'
    | '/manager/projects'
    | '/manager/requests'
    | '/manager/search'
    | '/manager/settings'
    | '/manager/stages'
    | '/manager/tasks'
    | '/manager/team'
    | '/manager/upload'
    | '/tenant/assistant'
    | '/tenant/dashboard'
    | '/tenant/documents'
    | '/tenant/meetings'
    | '/tenant/notifications'
    | '/tenant/photos'
    | '/tenant/project'
    | '/tenant/requests'
    | '/tenant/settings'
    | '/tenant/timeline'
    | '/company/projects/$projectId'
    | '/company/stages/$stageId'
    | '/manager/projects/$projectId'
    | '/manager/tasks/$taskId'
    | '/tenant/timeline/$stageId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/unauthorized'
    | '/_authenticated/profile'
    | '/_authenticated/settings'
    | '/_authenticated/company/activity'
    | '/_authenticated/company/apartments'
    | '/_authenticated/company/assistant'
    | '/_authenticated/company/dashboard'
    | '/_authenticated/company/documents'
    | '/_authenticated/company/managers'
    | '/_authenticated/company/meetings'
    | '/_authenticated/company/notifications'
    | '/_authenticated/company/projects'
    | '/_authenticated/company/requests'
    | '/_authenticated/company/search'
    | '/_authenticated/company/settings'
    | '/_authenticated/company/stages'
    | '/_authenticated/company/team'
    | '/_authenticated/company/tenants'
    | '/_authenticated/manager/activity'
    | '/_authenticated/manager/assistant'
    | '/_authenticated/manager/dashboard'
    | '/_authenticated/manager/documents'
    | '/_authenticated/manager/meetings'
    | '/_authenticated/manager/notifications'
    | '/_authenticated/manager/photos'
    | '/_authenticated/manager/projects'
    | '/_authenticated/manager/requests'
    | '/_authenticated/manager/search'
    | '/_authenticated/manager/settings'
    | '/_authenticated/manager/stages'
    | '/_authenticated/manager/tasks'
    | '/_authenticated/manager/team'
    | '/_authenticated/manager/upload'
    | '/_authenticated/tenant/assistant'
    | '/_authenticated/tenant/dashboard'
    | '/_authenticated/tenant/documents'
    | '/_authenticated/tenant/meetings'
    | '/_authenticated/tenant/notifications'
    | '/_authenticated/tenant/photos'
    | '/_authenticated/tenant/project'
    | '/_authenticated/tenant/requests'
    | '/_authenticated/tenant/settings'
    | '/_authenticated/tenant/timeline'
    | '/_authenticated/company/projects/$projectId'
    | '/_authenticated/company/stages/$stageId'
    | '/_authenticated/manager/projects/$projectId'
    | '/_authenticated/manager/tasks/$taskId'
    | '/_authenticated/tenant/timeline/$stageId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/company/activity': {
      id: '/_authenticated/company/activity'
      path: '/company/activity'
      fullPath: '/company/activity'
      preLoaderRoute: typeof AuthenticatedCompanyActivityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/company/apartments': {
      id: '/_authenticated/company/apartments'
      path: '/company/apartments'
      fullPath: '/company/apartments'
      preLoaderRoute: typeof AuthenticatedCompanyApartmentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/company/assistant': {
      id: '/_authenticated/company/assistant'
      path: '/company/assistant'
      fullPath: '/company/assistant'
      preLoaderRoute: typeof AuthenticatedCompanyAssistantRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/company/dashboard': {
      id: '/_authenticated/company/dashboard'
      path: '/company/dashboard'
      fullPath: '/company/dashboard'
      preLoaderRoute: typeof AuthenticatedCompanyDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/company/documents': {
      id: '/_authenticated/company/documents'
      path: '/company/documents'
      fullPath: '/company/documents'
      preLoaderRoute: typeof AuthenticatedCompanyDocumentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/company/managers': {
      id: '/_authenticated/company/managers'
      path: '/company/managers'
      fullPath: '/company/managers'
      preLoaderRoute: typeof AuthenticatedCompanyManagersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/company/meetings': {
      id: '/_authenticated/company/meetings'
      path: '/company/meetings'
      fullPath: '/company/meetings'
      preLoaderRoute: typeof AuthenticatedCompanyMeetingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/company/notifications': {
      id: '/_authenticated/company/notifications'
      path: '/company/notifications'
      fullPath: '/company/notifications'
      preLoaderRoute: typeof AuthenticatedCompanyNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/company/projects': {
      id: '/_authenticated/company/projects'
      path: '/company/projects'
      fullPath: '/company/projects'
      preLoaderRoute: typeof AuthenticatedCompanyProjectsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/company/requests': {
      id: '/_authenticated/company/requests'
      path: '/company/requests'
      fullPath: '/company/requests'
      preLoaderRoute: typeof AuthenticatedCompanyRequestsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/company/search': {
      id: '/_authenticated/company/search'
      path: '/company/search'
      fullPath: '/company/search'
      preLoaderRoute: typeof AuthenticatedCompanySearchRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/company/settings': {
      id: '/_authenticated/company/settings'
      path: '/company/settings'
      fullPath: '/company/settings'
      preLoaderRoute: typeof AuthenticatedCompanySettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/company/stages': {
      id: '/_authenticated/company/stages'
      path: '/company/stages'
      fullPath: '/company/stages'
      preLoaderRoute: typeof AuthenticatedCompanyStagesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/company/team': {
      id: '/_authenticated/company/team'
      path: '/company/team'
      fullPath: '/company/team'
      preLoaderRoute: typeof AuthenticatedCompanyTeamRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/company/tenants': {
      id: '/_authenticated/company/tenants'
      path: '/company/tenants'
      fullPath: '/company/tenants'
      preLoaderRoute: typeof AuthenticatedCompanyTenantsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/manager/activity': {
      id: '/_authenticated/manager/activity'
      path: '/manager/activity'
      fullPath: '/manager/activity'
      preLoaderRoute: typeof AuthenticatedManagerActivityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/manager/assistant': {
      id: '/_authenticated/manager/assistant'
      path: '/manager/assistant'
      fullPath: '/manager/assistant'
      preLoaderRoute: typeof AuthenticatedManagerAssistantRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/manager/dashboard': {
      id: '/_authenticated/manager/dashboard'
      path: '/manager/dashboard'
      fullPath: '/manager/dashboard'
      preLoaderRoute: typeof AuthenticatedManagerDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/manager/documents': {
      id: '/_authenticated/manager/documents'
      path: '/manager/documents'
      fullPath: '/manager/documents'
      preLoaderRoute: typeof AuthenticatedManagerDocumentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/manager/meetings': {
      id: '/_authenticated/manager/meetings'
      path: '/manager/meetings'
      fullPath: '/manager/meetings'
      preLoaderRoute: typeof AuthenticatedManagerMeetingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/manager/notifications': {
      id: '/_authenticated/manager/notifications'
      path: '/manager/notifications'
      fullPath: '/manager/notifications'
      preLoaderRoute: typeof AuthenticatedManagerNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/manager/photos': {
      id: '/_authenticated/manager/photos'
      path: '/manager/photos'
      fullPath: '/manager/photos'
      preLoaderRoute: typeof AuthenticatedManagerPhotosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/manager/projects': {
      id: '/_authenticated/manager/projects'
      path: '/manager/projects'
      fullPath: '/manager/projects'
      preLoaderRoute: typeof AuthenticatedManagerProjectsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/manager/requests': {
      id: '/_authenticated/manager/requests'
      path: '/manager/requests'
      fullPath: '/manager/requests'
      preLoaderRoute: typeof AuthenticatedManagerRequestsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/manager/search': {
      id: '/_authenticated/manager/search'
      path: '/manager/search'
      fullPath: '/manager/search'
      preLoaderRoute: typeof AuthenticatedManagerSearchRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/manager/settings': {
      id: '/_authenticated/manager/settings'
      path: '/manager/settings'
      fullPath: '/manager/settings'
      preLoaderRoute: typeof AuthenticatedManagerSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/manager/stages': {
      id: '/_authenticated/manager/stages'
      path: '/manager/stages'
      fullPath: '/manager/stages'
      preLoaderRoute: typeof AuthenticatedManagerStagesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/manager/tasks': {
      id: '/_authenticated/manager/tasks'
      path: '/manager/tasks'
      fullPath: '/manager/tasks'
      preLoaderRoute: typeof AuthenticatedManagerTasksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/manager/team': {
      id: '/_authenticated/manager/team'
      path: '/manager/team'
      fullPath: '/manager/team'
      preLoaderRoute: typeof AuthenticatedManagerTeamRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/manager/upload': {
      id: '/_authenticated/manager/upload'
      path: '/manager/upload'
      fullPath: '/manager/upload'
      preLoaderRoute: typeof AuthenticatedManagerUploadRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tenant/assistant': {
      id: '/_authenticated/tenant/assistant'
      path: '/tenant/assistant'
      fullPath: '/tenant/assistant'
      preLoaderRoute: typeof AuthenticatedTenantAssistantRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tenant/dashboard': {
      id: '/_authenticated/tenant/dashboard'
      path: '/tenant/dashboard'
      fullPath: '/tenant/dashboard'
      preLoaderRoute: typeof AuthenticatedTenantDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tenant/documents': {
      id: '/_authenticated/tenant/documents'
      path: '/tenant/documents'
      fullPath: '/tenant/documents'
      preLoaderRoute: typeof AuthenticatedTenantDocumentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tenant/meetings': {
      id: '/_authenticated/tenant/meetings'
      path: '/tenant/meetings'
      fullPath: '/tenant/meetings'
      preLoaderRoute: typeof AuthenticatedTenantMeetingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tenant/notifications': {
      id: '/_authenticated/tenant/notifications'
      path: '/tenant/notifications'
      fullPath: '/tenant/notifications'
      preLoaderRoute: typeof AuthenticatedTenantNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tenant/photos': {
      id: '/_authenticated/tenant/photos'
      path: '/tenant/photos'
      fullPath: '/tenant/photos'
      preLoaderRoute: typeof AuthenticatedTenantPhotosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tenant/project': {
      id: '/_authenticated/tenant/project'
      path: '/tenant/project'
      fullPath: '/tenant/project'
      preLoaderRoute: typeof AuthenticatedTenantProjectRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tenant/requests': {
      id: '/_authenticated/tenant/requests'
      path: '/tenant/requests'
      fullPath: '/tenant/requests'
      preLoaderRoute: typeof AuthenticatedTenantRequestsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tenant/settings': {
      id: '/_authenticated/tenant/settings'
      path: '/tenant/settings'
      fullPath: '/tenant/settings'
      preLoaderRoute: typeof AuthenticatedTenantSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tenant/timeline': {
      id: '/_authenticated/tenant/timeline'
      path: '/tenant/timeline'
      fullPath: '/tenant/timeline'
      preLoaderRoute: typeof AuthenticatedTenantTimelineRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/company/projects/$projectId': {
      id: '/_authenticated/company/projects/$projectId'
      path: '/$projectId'
      fullPath: '/company/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedCompanyProjectsProjectIdRouteImport
      parentRoute: typeof AuthenticatedCompanyProjectsRoute
    }
    '/_authenticated/company/stages/$stageId': {
      id: '/_authenticated/company/stages/$stageId'
      path: '/$stageId'
      fullPath: '/company/stages/$stageId'
      preLoaderRoute: typeof AuthenticatedCompanyStagesStageIdRouteImport
      parentRoute: typeof AuthenticatedCompanyStagesRoute
    }
    '/_authenticated/manager/projects/$projectId': {
      id: '/_authenticated/manager/projects/$projectId'
      path: '/$projectId'
      fullPath: '/manager/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedManagerProjectsProjectIdRouteImport
      parentRoute: typeof AuthenticatedManagerProjectsRoute
    }
    '/_authenticated/manager/tasks/$taskId': {
      id: '/_authenticated/manager/tasks/$taskId'
      path: '/$taskId'
      fullPath: '/manager/tasks/$taskId'
      preLoaderRoute: typeof AuthenticatedManagerTasksTaskIdRouteImport
      parentRoute: typeof AuthenticatedManagerTasksRoute
    }
    '/_authenticated/tenant/timeline/$stageId': {
      id: '/_authenticated/tenant/timeline/$stageId'
      path: '/$stageId'
      fullPath: '/tenant/timeline/$stageId'
      preLoaderRoute: typeof AuthenticatedTenantTimelineStageIdRouteImport
      parentRoute: typeof AuthenticatedTenantTimelineRoute
    }
  }
}

interface AuthenticatedCompanyProjectsRouteChildren {
  AuthenticatedCompanyProjectsProjectIdRoute: typeof AuthenticatedCompanyProjectsProjectIdRoute
}

const AuthenticatedCompanyProjectsRouteChildren: AuthenticatedCompanyProjectsRouteChildren =
  {
    AuthenticatedCompanyProjectsProjectIdRoute:
      AuthenticatedCompanyProjectsProjectIdRoute,
  }

const AuthenticatedCompanyProjectsRouteWithChildren =
  AuthenticatedCompanyProjectsRoute._addFileChildren(
    AuthenticatedCompanyProjectsRouteChildren,
  )

interface AuthenticatedCompanyStagesRouteChildren {
  AuthenticatedCompanyStagesStageIdRoute: typeof AuthenticatedCompanyStagesStageIdRoute
}

const AuthenticatedCompanyStagesRouteChildren: AuthenticatedCompanyStagesRouteChildren =
  {
    AuthenticatedCompanyStagesStageIdRoute:
      AuthenticatedCompanyStagesStageIdRoute,
  }

const AuthenticatedCompanyStagesRouteWithChildren =
  AuthenticatedCompanyStagesRoute._addFileChildren(
    AuthenticatedCompanyStagesRouteChildren,
  )

interface AuthenticatedManagerProjectsRouteChildren {
  AuthenticatedManagerProjectsProjectIdRoute: typeof AuthenticatedManagerProjectsProjectIdRoute
}

const AuthenticatedManagerProjectsRouteChildren: AuthenticatedManagerProjectsRouteChildren =
  {
    AuthenticatedManagerProjectsProjectIdRoute:
      AuthenticatedManagerProjectsProjectIdRoute,
  }

const AuthenticatedManagerProjectsRouteWithChildren =
  AuthenticatedManagerProjectsRoute._addFileChildren(
    AuthenticatedManagerProjectsRouteChildren,
  )

interface AuthenticatedManagerTasksRouteChildren {
  AuthenticatedManagerTasksTaskIdRoute: typeof AuthenticatedManagerTasksTaskIdRoute
}

const AuthenticatedManagerTasksRouteChildren: AuthenticatedManagerTasksRouteChildren =
  {
    AuthenticatedManagerTasksTaskIdRoute: AuthenticatedManagerTasksTaskIdRoute,
  }

const AuthenticatedManagerTasksRouteWithChildren =
  AuthenticatedManagerTasksRoute._addFileChildren(
    AuthenticatedManagerTasksRouteChildren,
  )

interface AuthenticatedTenantTimelineRouteChildren {
  AuthenticatedTenantTimelineStageIdRoute: typeof AuthenticatedTenantTimelineStageIdRoute
}

const AuthenticatedTenantTimelineRouteChildren: AuthenticatedTenantTimelineRouteChildren =
  {
    AuthenticatedTenantTimelineStageIdRoute:
      AuthenticatedTenantTimelineStageIdRoute,
  }

const AuthenticatedTenantTimelineRouteWithChildren =
  AuthenticatedTenantTimelineRoute._addFileChildren(
    AuthenticatedTenantTimelineRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedCompanyActivityRoute: typeof AuthenticatedCompanyActivityRoute
  AuthenticatedCompanyApartmentsRoute: typeof AuthenticatedCompanyApartmentsRoute
  AuthenticatedCompanyAssistantRoute: typeof AuthenticatedCompanyAssistantRoute
  AuthenticatedCompanyDashboardRoute: typeof AuthenticatedCompanyDashboardRoute
  AuthenticatedCompanyDocumentsRoute: typeof AuthenticatedCompanyDocumentsRoute
  AuthenticatedCompanyManagersRoute: typeof AuthenticatedCompanyManagersRoute
  AuthenticatedCompanyMeetingsRoute: typeof AuthenticatedCompanyMeetingsRoute
  AuthenticatedCompanyNotificationsRoute: typeof AuthenticatedCompanyNotificationsRoute
  AuthenticatedCompanyProjectsRoute: typeof AuthenticatedCompanyProjectsRouteWithChildren
  AuthenticatedCompanyRequestsRoute: typeof AuthenticatedCompanyRequestsRoute
  AuthenticatedCompanySearchRoute: typeof AuthenticatedCompanySearchRoute
  AuthenticatedCompanySettingsRoute: typeof AuthenticatedCompanySettingsRoute
  AuthenticatedCompanyStagesRoute: typeof AuthenticatedCompanyStagesRouteWithChildren
  AuthenticatedCompanyTeamRoute: typeof AuthenticatedCompanyTeamRoute
  AuthenticatedCompanyTenantsRoute: typeof AuthenticatedCompanyTenantsRoute
  AuthenticatedManagerActivityRoute: typeof AuthenticatedManagerActivityRoute
  AuthenticatedManagerAssistantRoute: typeof AuthenticatedManagerAssistantRoute
  AuthenticatedManagerDashboardRoute: typeof AuthenticatedManagerDashboardRoute
  AuthenticatedManagerDocumentsRoute: typeof AuthenticatedManagerDocumentsRoute
  AuthenticatedManagerMeetingsRoute: typeof AuthenticatedManagerMeetingsRoute
  AuthenticatedManagerNotificationsRoute: typeof AuthenticatedManagerNotificationsRoute
  AuthenticatedManagerPhotosRoute: typeof AuthenticatedManagerPhotosRoute
  AuthenticatedManagerProjectsRoute: typeof AuthenticatedManagerProjectsRouteWithChildren
  AuthenticatedManagerRequestsRoute: typeof AuthenticatedManagerRequestsRoute
  AuthenticatedManagerSearchRoute: typeof AuthenticatedManagerSearchRoute
  AuthenticatedManagerSettingsRoute: typeof AuthenticatedManagerSettingsRoute
  AuthenticatedManagerStagesRoute: typeof AuthenticatedManagerStagesRoute
  AuthenticatedManagerTasksRoute: typeof AuthenticatedManagerTasksRouteWithChildren
  AuthenticatedManagerTeamRoute: typeof AuthenticatedManagerTeamRoute
  AuthenticatedManagerUploadRoute: typeof AuthenticatedManagerUploadRoute
  AuthenticatedTenantAssistantRoute: typeof AuthenticatedTenantAssistantRoute
  AuthenticatedTenantDashboardRoute: typeof AuthenticatedTenantDashboardRoute
  AuthenticatedTenantDocumentsRoute: typeof AuthenticatedTenantDocumentsRoute
  AuthenticatedTenantMeetingsRoute: typeof AuthenticatedTenantMeetingsRoute
  AuthenticatedTenantNotificationsRoute: typeof AuthenticatedTenantNotificationsRoute
  AuthenticatedTenantPhotosRoute: typeof AuthenticatedTenantPhotosRoute
  AuthenticatedTenantProjectRoute: typeof AuthenticatedTenantProjectRoute
  AuthenticatedTenantRequestsRoute: typeof AuthenticatedTenantRequestsRoute
  AuthenticatedTenantSettingsRoute: typeof AuthenticatedTenantSettingsRoute
  AuthenticatedTenantTimelineRoute: typeof AuthenticatedTenantTimelineRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedCompanyActivityRoute: AuthenticatedCompanyActivityRoute,
  AuthenticatedCompanyApartmentsRoute: AuthenticatedCompanyApartmentsRoute,
  AuthenticatedCompanyAssistantRoute: AuthenticatedCompanyAssistantRoute,
  AuthenticatedCompanyDashboardRoute: AuthenticatedCompanyDashboardRoute,
  AuthenticatedCompanyDocumentsRoute: AuthenticatedCompanyDocumentsRoute,
  AuthenticatedCompanyManagersRoute: AuthenticatedCompanyManagersRoute,
  AuthenticatedCompanyMeetingsRoute: AuthenticatedCompanyMeetingsRoute,
  AuthenticatedCompanyNotificationsRoute:
    AuthenticatedCompanyNotificationsRoute,
  AuthenticatedCompanyProjectsRoute:
    AuthenticatedCompanyProjectsRouteWithChildren,
  AuthenticatedCompanyRequestsRoute: AuthenticatedCompanyRequestsRoute,
  AuthenticatedCompanySearchRoute: AuthenticatedCompanySearchRoute,
  AuthenticatedCompanySettingsRoute: AuthenticatedCompanySettingsRoute,
  AuthenticatedCompanyStagesRoute: AuthenticatedCompanyStagesRouteWithChildren,
  AuthenticatedCompanyTeamRoute: AuthenticatedCompanyTeamRoute,
  AuthenticatedCompanyTenantsRoute: AuthenticatedCompanyTenantsRoute,
  AuthenticatedManagerActivityRoute: AuthenticatedManagerActivityRoute,
  AuthenticatedManagerAssistantRoute: AuthenticatedManagerAssistantRoute,
  AuthenticatedManagerDashboardRoute: AuthenticatedManagerDashboardRoute,
  AuthenticatedManagerDocumentsRoute: AuthenticatedManagerDocumentsRoute,
  AuthenticatedManagerMeetingsRoute: AuthenticatedManagerMeetingsRoute,
  AuthenticatedManagerNotificationsRoute:
    AuthenticatedManagerNotificationsRoute,
  AuthenticatedManagerPhotosRoute: AuthenticatedManagerPhotosRoute,
  AuthenticatedManagerProjectsRoute:
    AuthenticatedManagerProjectsRouteWithChildren,
  AuthenticatedManagerRequestsRoute: AuthenticatedManagerRequestsRoute,
  AuthenticatedManagerSearchRoute: AuthenticatedManagerSearchRoute,
  AuthenticatedManagerSettingsRoute: AuthenticatedManagerSettingsRoute,
  AuthenticatedManagerStagesRoute: AuthenticatedManagerStagesRoute,
  AuthenticatedManagerTasksRoute: AuthenticatedManagerTasksRouteWithChildren,
  AuthenticatedManagerTeamRoute: AuthenticatedManagerTeamRoute,
  AuthenticatedManagerUploadRoute: AuthenticatedManagerUploadRoute,
  AuthenticatedTenantAssistantRoute: AuthenticatedTenantAssistantRoute,
  AuthenticatedTenantDashboardRoute: AuthenticatedTenantDashboardRoute,
  AuthenticatedTenantDocumentsRoute: AuthenticatedTenantDocumentsRoute,
  AuthenticatedTenantMeetingsRoute: AuthenticatedTenantMeetingsRoute,
  AuthenticatedTenantNotificationsRoute: AuthenticatedTenantNotificationsRoute,
  AuthenticatedTenantPhotosRoute: AuthenticatedTenantPhotosRoute,
  AuthenticatedTenantProjectRoute: AuthenticatedTenantProjectRoute,
  AuthenticatedTenantRequestsRoute: AuthenticatedTenantRequestsRoute,
  AuthenticatedTenantSettingsRoute: AuthenticatedTenantSettingsRoute,
  AuthenticatedTenantTimelineRoute:
    AuthenticatedTenantTimelineRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  UnauthorizedRoute: UnauthorizedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
